events {}

http {
  upstream backend_pool {
    server backend-prod-1:8000;
    server backend-prod-2:8000;
  }

  server {
    listen 80;

    location / {
      proxy_pass         http://backend_pool;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_read_timeout 60s;
    }
  }
}
